// Code generated by "stringer -linecomment -type Kind"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindNone-0]
	_ = x[KindGeneric-1]
	_ = x[KindFunc-2]
	_ = x[KindNumber-3]
	_ = x[KindString-4]
	_ = x[KindBool-5]
	_ = x[KindInt-6]
	_ = x[KindFloat-7]
	_ = x[KindChan-8]
	_ = x[KindTuple-9]
	_ = x[KindClass-10]
	_ = x[KindEnum-11]
	_ = x[KindCase-12]
	_ = x[KindAlias-13]
}

const _Kind_name = "nonegenericfunctionnumberstringboolintfloatchantupleclassenumcasealias"

var _Kind_index = [...]uint8{0, 4, 11, 19, 25, 31, 35, 38, 43, 47, 52, 57, 61, 65, 70}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
