// Code generated by "stringer -type Property"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Assignable-1]
}

const _Property_name = "Assignable"

var _Property_index = [...]uint8{0, 10}

func (i Property) String() string {
	i -= 1
	if i < 0 || i >= Property(len(_Property_index)-1) {
		return "Property(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Property_name[_Property_index[i]:_Property_index[i+1]]
}
