// Code generated by "stringer -linecomment -type Modifiers"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModifierPublic-1]
	_ = x[ModifierOverride-4]
	_ = x[ModifierStatic-16]
}

const (
	_Modifiers_name_0 = "pub"
	_Modifiers_name_1 = "override"
	_Modifiers_name_2 = "static"
)

func (i Modifiers) String() string {
	switch {
	case i == 1:
		return _Modifiers_name_0
	case i == 4:
		return _Modifiers_name_1
	case i == 16:
		return _Modifiers_name_2
	default:
		return "Modifiers(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
