// Code generated by "stringer -linecomment -type Op"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpNone-0]
	_ = x[OpAsgn-1]
	_ = x[OpAddAsgn-2]
	_ = x[OpSubAsgn-3]
	_ = x[OpMulAsgn-4]
	_ = x[OpDivAsgn-5]
	_ = x[OpModAsgn-6]
	_ = x[OpPowAsgn-7]
	_ = x[OpGe-8]
	_ = x[OpLe-9]
	_ = x[OpAnd-10]
	_ = x[OpOr-11]
	_ = x[OpEq-12]
	_ = x[OpNe-13]
	_ = x[OpSub-14]
	_ = x[OpAdd-15]
	_ = x[OpMul-16]
	_ = x[OpDiv-17]
	_ = x[OpLt-18]
	_ = x[OpGt-19]
	_ = x[OpMod-20]
	_ = x[OpPow-21]
	_ = x[OpNot-22]
	_ = x[OpSend-23]
	_ = x[OpBitOr-24]
	_ = x[OpBitAnd-25]
}

const _Op_name = "=+=-=*=/=%=^=>=<=&&||==!=-+*/<>%^!->|&"

var _Op_index = [...]uint8{0, 0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38}

func (i Op) String() string {
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
